### ISSUE TITLE
Is there a reason why package-lock.json is in .gitignore while yarn.lock is not?

### ISSUE THREAD

**Issue by tknappra** [preactjs-templates/netlify#8]

**Comment by tknappra** [comment]
PS, 
I also noticed that size-plugin.json shows up in the root directory after building locally. So, I added that to .gitignore.

PPS,
Thanks for making this Netlify CMS template! 😃

**Comment by rschristian** [comment]
Nope, no reason for that. Someone just happened to be using NPM rather than Yarn, and didn't think to add it.

You might actually want to track `size-plugin.json`. I usually don't, but the [Preact website](https://github.com/preactjs/preact-www) for instance does, as it lets you keep track of bundle changes across a team / many contributors. Something to keep in mind.

**Comment by tknappra** [comment]
@rschristian Thanks for getting back!

I'll remove size-plugin.json from .gitignore, then. I think that sounds potentially useful. 👍 

Honestly, I've never really known the truth about putting package-lock.json in .gitignore... I've found some sources that say you should some that say you shouldn't... I was semi-wondering if there was something special going on here that I could learn from.

But, it looks like whoever used npm here at that time might just be a "put package-lock.json in .gitignore" kind of person, sort of speak haha.

Thanks again!

**Comment by tknappra** [comment]
PS
I personally always track package-lock.json! (not in .gitignore)

But, for my Preact Netlify CMS project, I decided to put both yarn.lock and package-lock.json inside .gitignore because I saw package-lock.json in there.

**Comment by rschristian** [comment]
FWIW, NPM itself is now of the opinion that [they should always be tracked by Git](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#description)

>This file is intended to be committed into source repositories, and serves various purposes...

as is [yarn](https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-check-into-source-control)

> All yarn.lock files should be checked into source control (e.g. git or mercurial).

I believe NPM used to be "do what you want" about it, but seems to have changed their minds. 

We don't have this set on other repos, so is probably worth fixing. I'm guessing this was a mistake done to keep the template's lock file from being committed to this repository, rather than for all apps.

**Comment by tknappra** [comment]
@rschristian Thanks for informing! I appreciate it!

Hmm.. Interesting.. I can actually kind of see it making sense for a "template" (vs an "app") not to have package-lock.json, but then once the template is used and turned into an app that people should commit their package-lock.json. 

Just so that, in theory, people who use the template would be using the latest versions of libraries (the minor versions, anyway)? 🤔 I can see why someone might have put it in there. I don't know the "best practice" on that though haha.

Anyway, I'll remove both from .gitignore in my repo! 

Thanks again for the awesome Preact template! I'm an advocate of using small npm packages for keeping bundle sizes low, and Preact is just that!

**Comment by rschristian** [comment]
> Hmm.. Interesting.. I can actually kind of see it making sense for a "template" (vs an "app") not to have package-lock.json, but then once the template is used and turned into an app that people should commit their package-lock.json.

Yeah the other templates have this set up correctly, the `.gitignore` with the `package-lock.json` needs to be one level higher, outside of the actual template is all. Just need to fix that. 

It's currently where it is by mistake, nothing more. It's so we (when updating the template) don't push a lock file that would mess with new app setup.
